# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c093675249be4856f8984dad9e4984f15765dd80eaf60c8b01028968601366196089c8f792097fb884595c5be1a6dcec25a39dd4f6aa99cb82a94684026a2a9e

test:
  secret_key_base: 6bb13f27a184419b664f337648c95ecc6502333bef7f71e50c2b6605527b57c679541fe023933119b536898d4ff2af3f15a717a7645a79a7c3811523952357ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
